darwinia-network/darwinia-common

.maintain/bootstrap.sh, .maintain/darwinia-ensure-deps.sh, .maintain/hooks/pre-commit
- copy some maintain scripts from Darwinia
=> update maintain scripts

bin/node-template/runtime/src/lib.rs, frame/chainrelay/eth/backing/src/lib.rs, frame/chainrelay/eth/backing/src/mock.rs, frame/chainrelay/eth/offchain/src/mock.rs, frame/chainrelay/eth/relay/src/lib.rs, frame/chainrelay/eth/relay/src/mock.rs, frame/staking/src/lib.rs, frame/treasury/src/lib.rs
=> Refactor eth network const and subkey prefix

Cargo.lock, bin/node-template/runtime/src/lib.rs, frame/balances/src/lib.rs, frame/balances/src/tests_local.rs, frame/chainrelay/eth/backing/src/mock.rs, frame/claims/src/lib.rs, frame/elections-phragmen/src/lib.rs, frame/staking/src/darwinia_tests.rs, frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/support/Cargo.toml, frame/support/src/lib.rs, frame/support/src/traits.rs, frame/treasury/src/mock.rs, frame/vesting/src/lib.rs
Support up to 16 different currency. 
If you have a lot of currency, the `DustLost` event will be a little annoy.
=> update: new `DustCollector`

bin/node-template/runtime/src/lib.rs, frame/chainrelay/eth/offchain/src/lib.rs, frame/chainrelay/eth/offchain/src/mock.rs
- Get the token from offchain db
=> Get token from offchain db

bin/node-template/runtime/src/lib.rs, frame/chainrelay/eth/backing/src/lib.rs, frame/chainrelay/eth/backing/src/mock.rs, frame/chainrelay/eth/backing/src/tests.rs, frame/elections-phragmen/src/lib.rs, frame/staking/src/lib.rs, frame/support/src/traits.rs, frame/treasury/src/lib.rs
=> Refactor backing Module

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/darwinia_types.json, bin/node-template/runtime/polkadot_compatible_types.json, docs/CODEOWNERS, frame/balances/Cargo.toml, frame/balances/rpc/Cargo.toml, frame/balances/rpc/runtime-api/Cargo.toml, frame/balances/src/lib.rs, frame/bridge/eth/backing/Cargo.toml, frame/bridge/eth/offchain/Cargo.toml, frame/bridge/eth/relay/Cargo.toml, frame/claims/Cargo.toml, frame/elections-phragmen/Cargo.toml, frame/header-mmr/Cargo.toml, frame/staking/Cargo.toml, frame/staking/src/lib.rs, frame/support/Cargo.toml, frame/treasury/Cargo.toml, frame/treasury/src/lib.rs, primitives/eth-primitives/Cargo.toml, primitives/merkle-patricia-trie/Cargo.toml
Add Event for `try_claim_deposits_with_punish`
Fix #131
=> Staking Upgrade

Cargo.lock, bin/node-template/node/Cargo.toml, bin/node-template/node/res/dags_merkle_roots.json, bin/node-template/node/src/chain_spec.rs, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/build.rs, frame/balances/Cargo.toml, frame/balances/rpc/Cargo.toml, frame/balances/rpc/runtime-api/Cargo.toml, frame/bridge/eth/backing/Cargo.toml, frame/bridge/eth/offchain/Cargo.toml, frame/bridge/eth/relay/Cargo.toml, frame/bridge/eth/relay/build.rs, frame/bridge/eth/relay/src/lib.rs, frame/bridge/eth/relay/src/mock.rs, frame/claims/Cargo.toml, frame/claims/src/lib.rs, frame/elections-phragmen/Cargo.toml, frame/header-mmr/Cargo.toml, frame/header-mmr/src/lib.rs, frame/staking/Cargo.toml, frame/staking/src/lib.rs, frame/staking/src/slashing.rs, frame/support/Cargo.toml, frame/support/src/macros.rs, frame/treasury/Cargo.toml, primitives/eth-primitives/Cargo.toml, primitives/merkle-patricia-trie/Cargo.toml
1. remove build-spec feature
2. add some default dag merkle roots for eth-relay
3. log warning if empty claims list
=> Update Genesis and Fix Bugs

Cargo.lock, Cargo.toml, frame/bridge/eth/backing/Cargo.toml, frame/bridge/eth/backing/src/mock.rs, frame/bridge/eth/backing/src/tests.rs, frame/bridge/eth/offchain/Cargo.toml, frame/bridge/eth/offchain/src/lib.rs, frame/bridge/eth/relay/Cargo.toml, frame/bridge/eth/relay/src/lib.rs, frame/bridge/eth/relay/src/mock.rs, frame/claims/Cargo.toml, frame/claims/src/address.rs, frame/claims/src/lib.rs, frame/support/src/lib.rs, frame/support/src/macros.rs, frame/support/src/tests.rs, primitives/array-bytes/Cargo.toml, primitives/array-bytes/src/lib.rs, primitives/eth-primitives/Cargo.toml, primitives/eth-primitives/src/header.rs, primitives/eth-primitives/src/receipt.rs
move to another pr:
~~- [ ] http client for runtime~~
~~- [ ] json parser for runtime~~
=> Runtime Utility for Array/Bytes

Cargo.lock, frame/bridge/ethereum/relay/src/lib.rs, frame/bridge/relayer-game/Cargo.toml, frame/bridge/relayer-game/src/lib.rs, frame/bridge/relayer-game/src/mock.rs, frame/support/src/lib.rs, frame/support/src/structs.rs, frame/support/src/traits.rs
=> Relayer Game Tests Prepare

frame/staking/src/darwinia_tests.rs, frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/substrate_tests.rs
Due to the master branch are develop relayer game.
This hotfix should be merged into darwinia-master directly.
=> Hotfix Underflow

Cargo.lock, bin/node-template/node/src/rpc.rs, bin/node-template/runtime/src/lib.rs, frame/header-mmr/Cargo.toml, frame/header-mmr/rpc/runtime-api/src/lib.rs, frame/header-mmr/rpc/src/lib.rs, frame/header-mmr/src/lib.rs, frame/header-mmr/src/tests.rs
=> Fix mmr size in gen proof, Fixed #177

Cargo.lock, bin/node-template/node/src/chain_spec.rs, bin/node-template/runtime/Cargo.toml, bin/node-template/runtime/src/lib.rs, frame/bridge/relayer-game/src/lib.rs, frame/bridge/relayer-game/src/mock.rs, frame/bridge/relayer-game/src/tests.rs
=> Relayer Game Guard System

frame/balances/src/lib.rs, frame/balances/src/tests.rs, frame/support/src/traits.rs
=> Implement Extend Lock

.github/workflows/ci.yml, bin/node-template/runtime/darwinia_types.json, bin/node-template/runtime/polkadot_compatible_types.json, bin/node-template/runtime/src/lib.rs, frame/balances/src/lib.rs, frame/staking/src/lib.rs
1. Correct staking payout
1. Keep reward destination same as polkadot, I think no people want to make a default promise bond. If they want just call the `deposit_extra`
=> Correct Staking Payout

Cargo.lock, bin/node-template/node/Cargo.toml, frame/bridge/ethereum/relay/src/lib.rs, frame/bridge/relayer-game/src/lib.rs, frame/bridge/relayer-game/src/mock.rs, frame/bridge/relayer-game/src/tests.rs, primitives/relay/src/lib.rs
Relayer Games tests here. #268
=> Relayer Game Fixes

bin/node-template/runtime/polkadot-compatible-types.json, bin/node-template/runtime/src/lib.rs, bin/node-template/runtime/types.json, frame/bridge/crab/issuing/src/mock.rs, frame/bridge/ethereum/backing/src/test_with_relay.rs, frame/bridge/ethereum/linear-relay/src/lib.rs, frame/bridge/ethereum/linear-relay/src/tests.rs, frame/bridge/ethereum/relay/src/lib.rs, frame/bridge/ethereum/relay/src/mock.rs, frame/bridge/relayer-game/src/lib.rs, frame/bridge/relayer-game/src/mock.rs, frame/bridge/relayer-game/src/tests.rs, primitives/relay/src/lib.rs
=> Refactor Challenge Time & Guard System

frame/bridge/ethereum/backing/src/lib.rs
=> Expose Advanced Fee for Front-End Usage

bin/node/runtime/pangolin/polkadot-compatible-types.json, bin/node/runtime/pangolin/types.json, frame/bridge/ethereum/backing/src/lib.rs, frame/bridge/ethereum/backing/src/test_with_relay.rs, frame/bridge/relay-authorities/src/lib.rs, frame/bridge/relay-authorities/src/mock.rs, frame/bridge/relay-authorities/src/test.rs, primitives/relay/src/relay_authorities.rs
Need a custom migration for Pangolin
=> Hash Message

Cargo.lock, frame/bridge/ethereum/backing/src/lib.rs, frame/bridge/relay-authorities/src/lib.rs, frame/bridge/relay-authorities/src/mock.rs, frame/bridge/relay-authorities/src/test.rs
1. wrong term in the event
1. insufficient fee while paying for syncing-bridger
=> Fix Relay Authorities Bugs

frame/bridge/relay-authorities/src/lib.rs, frame/bridge/relay-authorities/src/test.rs
=> Fix Signed Authorities Ratio

bin/node/cli/src/chain_spec.rs
@WoeOm Please check these changes.
=> update: spec style

frame/bridge/ethereum/backing/src/lib.rs
Prevent this: https://crab.subscan.io/extrinsic/3712196-2
=> correct: balance to lock value

Cargo.lock, bin/node/runtime/pangolin/src/lib.rs, frame/dvm/src/account_basic.rs, frame/dvm/src/mock.rs, frame/evm/precompile/contracts/withdraw/src/lib.rs, frame/evm/src/lib.rs, frame/evm/src/tests.rs
=> Support kton for dvm

bin/node/runtime/pangolin/src/lib.rs, script_tests/tests/1_test-transfer.js, script_tests/tests/test-rpc-constants.js
=> Set min gas price value

script_tests/tests/3_test-rpc-filter.js
https://github.com/darwinia-network/darwinia-common/pull/428#issue-548090094
=> DVM  test filter rpc

bin/node/cli/src/chain_spec.rs, bin/node/runtime/pangolin/src/evm.rs, script_tests/tests/1_test-transfer.js, script_tests/tests/test-bloom.js, script_tests/tests/test-gas.js, script_tests/tests/test-rpc-constants.js
=> Fix transfer gas price

Cargo.lock, frame/dvm/src/lib.rs, frame/evm/precompile/contracts/kton/Cargo.toml, frame/evm/precompile/contracts/kton/src/lib.rs, frame/evm/src/lib.rs, script_tests/tests/test_kton.js
This pr fix #575 #578 and implemented based on #577. Although this pr must wait for #577 merged. It is ready for reviewing now.
This precompile is **critical** to the whole system, so please make sure you spend some time reviewing it.
@HackFisher @hujw77 @AurevoirXavier 
---
With regard to the design of the KTON precompile, I think it necessary to write the following material to help those who are not familiar with this precompile contract to understand it.
Precompile contracts are special contracts that have a fixed address and the user can send transactions to call methods in the contract. The KTON contract we are discussing is a pre-compiled contract with a fixed address of `0000000000000000000000000000000000000016`.
The purpose of the KTON precompile is to support the transfer of the …
=> Refactor kton precompile

Cargo.lock, bin/node/runtime/pangolin/src/lib.rs, frame/support/src/lib.rs, frame/support/src/traits.rs
1. Update format
2. Downgrade `jsonrpsee` for `try-runtime`
=> Code Clean

frame/balances/src/lib.rs, frame/balances/src/tests.rs, frame/balances/src/tests_local.rs
=> Dust Collection Hook

Cargo.lock, bin/node/runtime/pangolin/src/pallets/balances.rs, client/dvm/rpc/Cargo.toml, client/dvm/rpc/src/lib.rs, frame/evm/src/lib.rs, frame/evm/src/tests.rs, script_tests/tests/1_test-transfer.js
1. Change `ExistentialDeposit` from 1 COIN to zero
2. EVM pallet code clean
=> Release Pangolin.221

frame/bridge/ethereum/backing/src/lib.rs
Keep some RING is enough.
NOTE: this won't affect any existing chain.
=> Correct ED

Cargo.lock, bin/node/runtime/pangolin/Cargo.toml, bin/node/runtime/pangolin/src/lib.rs, bin/node/runtime/pangolin/src/pallets/mod.rs, bin/node/runtime/pangolin/src/pallets/shift_session_manager.rs
we don't need pallet-shift-session-manager
related: https://github.com/paritytech/parity-bridges-common/issues/970
=> remove pallet-shift-session-manager

bin/node/runtime/pangolin/src/lib.rs
issue: https://github.com/darwinia-network/darwinia-common/pull/637
=> Expose SudoCall

frame/bridge/ethereum/backing/src/lib.rs, frame/bridge/ethereum/issuing/src/lib.rs, frame/bridge/ethereum/relay/src/lib.rs, frame/bridge/relay-authorities/src/lib.rs, frame/bridge/relayer-game/src/lib.rs, frame/staking/src/lib.rs
=> `BlockNumber<T>` to `BlockNumberFor<T>`

bin/node/runtime/pangolin/polkadot-compatible-types.json, bin/node/runtime/pangolin/types.json
Please link the companion PR here.
cc @WoeOm
=> Update Metadata Types

frame/bridge/ethereum-bsc/Cargo.toml, primitives/chain-bsc/Cargo.toml, primitives/chain-bsc/src/lib.rs
=> Serde for `std`

bin/node/cli/src/service.rs, client/dvm/mapping-sync/src/worker.rs
Close #716 
[Companion pr in Darwinia](https://github.com/darwinia-network/darwinia/pull/685)
=> Enable mapping-worker only in archive mode

bin/node/runtime/pangolin/src/lib.rs, frame/democracy/src/lib.rs, frame/dvm-dynamic-fee/src/lib.rs
Avoid too many useless events on Crab.
=> Cherry Pick #642

bin/node/runtime/pangolin/polkadot-compatible-types.json, bin/node/runtime/pangolin/types.json
Which I missed in #708.
cc @freehere107 @sxlwar @WoeOm
=> Update `EthereumHeader` Type

bin/node/runtime/pangolin/src/pallets/ethereum_issuing.rs, bin/node/runtime/pangolin/src/pallets/evm_.rs, frame/bridge/ethereum/issuing/Cargo.toml, frame/bridge/ethereum/issuing/src/lib.rs, frame/evm/precompile/contracts/encoder/Cargo.toml, primitives/contract/src/ethereum_backing.rs, primitives/contract/src/mapping_token_factory.rs
1. Clippy fix
2. Remove useless associated type
3. Code format
=> Update e2d refactor branch

frame/bridge/ethereum/issuing/src/lib.rs, frame/bridge/s2s/backing/src/lib.rs, frame/bridge/s2s/issuing/src/lib.rs
=> Add `transactional` attribute to some call

frame/dvm/README.md
=> Add DVM README

bin/node/runtime/pangolin/src/lib.rs
Companion for Darwinia: https://github.com/darwinia-network/darwinia/pull/710
=> Correct `ProposalCount` & `Approvals`

node/service/res/pangoro/pangoro.json, node/service/src/chain_spec/pangoro.rs
=> Update Pangoro Token Symbol

node/primitives/bridge/src/lib.rs
change follow https://github.com/paritytech/parity-bridges-common/pull/996
=> Rename `messages_dispatch_weight` to `message_details`

frame/dvm/src/lib.rs
https://github.com/paritytech/frontier/pull/465
=> Companion for #frontier-465

docs/Relayer Fee Market.md
The edition used for Parity Milestone Checkin.
=> Add the design of Relayer Fee Market

Cargo.lock, node/runtime/pangolin/Cargo.toml, node/runtime/pangoro/Cargo.toml, node/runtime/pangoro/build.rs
Remove unused feature and update WASM build version.
=> Update Feature and WASM Builder

node/primitives/bridge/src/lib.rs, node/runtime/pangolin/src/bridges/substrate/pangoro_messages.rs, node/runtime/pangolin/src/pallets/bridge_messages.rs, node/runtime/pangolin/src/pallets/from_substrate_issuing_.rs, node/runtime/pangoro/src/pallets/bridge_message.rs, node/runtime/pangoro/src/pallets/to_substrate_backing_.rs, node/runtime/pangoro/src/pangolin_messages.rs
=> Move `PANGORO_PANGOLIN_LANE` to `bridge-primitives` and Renew `LaneId`

frame/dvm/src/lib.rs, frame/dvm/src/tests.rs, frame/wormhole/backing/s2s/src/lib.rs
Enrich the internal transaction dispatch error type.
=> Update internal transaction dispatch error

.github/workflows/release.yml, vercel.json
Polish some code.
Also, fix https://github.com/darwinia-network/darwinia-common/runs/3682468744.
=> Polish Rustdoc CI

frame/bridge/relay-authorities/src/lib.rs, node/runtime/pangolin/polkadot-compatible-types.json, node/runtime/pangolin/types.json, primitives/relay/src/relay_authorities.rs
=> Correct `MmrRootToSign` Type

.github/workflows/ci.yml
=> Format Output

Cargo.lock, frame/bridge/relayer-game/Cargo.toml, frame/bridge/relayer-game/src/lib.rs, frame/bridge/relayer-game/src/mock.rs, frame/bridge/relayer-game/src/tests.rs
Error detail: https://github.com/darwinia-network/darwinia-common/runs/4148632029?check_suite_focus=true
=> Improve Log and Test

.github/workflows/ci.yml
=> Disable CI for Draft Pull Request

.github/workflows/ci.yml, .maintain/purge-large-cache.sh
1. Only running on code/genesis/ci changed.
2. Use matrix.
3. Optimize cache.
4. Remove compress step.
=> Improve CI

Cargo.lock, frame/wormhole/issuing/s2s/Cargo.toml
I find this issue when doing the DVM debug task.
=> Update crate version

node/runtime/pangolin/Cargo.toml, node/runtime/pangolin/build.rs, node/runtime/pangolin/src/lib.rs, node/runtime/pangoro/Cargo.toml, node/runtime/pangoro/build.rs, node/runtime/pangoro/src/lib.rs
Disable WASM for some use-cases.
e.g Speed up the bridger compile.
=> Feature Disable WASM

node/runtime/pangolin/src/lib.rs, node/runtime/pangoro/src/lib.rs
Close #999.
@AsceticBear Try this.
=> Fix Benchmark

Cargo.lock, client/dvm/tracer/Cargo.toml, client/dvm/tracer/src/listeners/call_list.rs, client/dvm/tracer/src/listeners/raw.rs, primitives/evm/trace/apis/Cargo.toml, primitives/evm/trace/apis/src/lib.rs, primitives/evm/trace/events/Cargo.toml, primitives/evm/trace/events/src/evm.rs, primitives/evm/trace/events/src/lib.rs, primitives/evm/trace/events/src/runtime.rs, primitives/evm/trace/ext/Cargo.toml, primitives/evm/trace/ext/src/lib.rs, primitives/evm/trace/tracer/Cargo.toml, primitives/evm/trace/tracer/src/lib.rs
=> Evm tracing companion

Cargo.lock, node/runtime/pangolin/src/lib.rs
paritytech/substrate#9080
paritytech/substrate#9711
paritytech/substrate#9115
https://github.com/Phala-Network/khala-parachain/pull/54
=> Add Migrations

README.md, shell.nix
- Add shell.nix
- Add build for nixos support
- Fix typo
=> Build for nixos support

frame/bridge/bsc/src/benchmarking.rs, frame/bridge/bsc/src/weight.rs, frame/evm/precompile/contracts/bridge/bsc/src/lib.rs, frame/transaction-pause/src/weights.rs, primitives/contract/src/bsc_light_client.rs, primitives/ethereum/src/storage.rs, primitives/ethereum/src/tests.rs
Those files are mergedd after the last copyright clean pr.
=> Update bsc related files copyright

node/runtime/pangolin/src/lib.rs
Sry forgot to remove some unused constants in #1051.
=> Remove Unused Constants

Cargo.toml
Speed up development.
Only enable on release-lto.
```
cargo build --profile release-lto
```
=> LTO Profile

node/service/res/pangolin/pangolin.json, node/service/res/pangoro/pangoro.json
=> Update Pangoro/Pangolin Bootnodes

frame/beefy-gadget/src/lib.rs, node/runtime/pangolin/src/lib.rs, node/runtime/pangoro/src/lib.rs, primitives/beefy/src/network_ids.rs
=> Update BEEFY Specification

node/service/src/service/mod.rs
=> Register BEEFY Networking Protocol

client/dvm/rpc/src/debug.rs
Close #1076. Essentially, this is a companion pull request.
=> Fix the potential panic

Cargo.lock, node/runtime/pangolin/Cargo.toml, node/runtime/pangoro/Cargo.toml, primitives/evm-trace/apis/Cargo.toml, primitives/evm-trace/ext/Cargo.toml, primitives/evm-trace/tracer/Cargo.toml
=> Fix Tracing Runtime Build

Cargo.lock, client/dvm/db/Cargo.toml, client/dvm/rpc/Cargo.toml, frame/dvm/Cargo.toml, frame/dvm/rpc/Cargo.toml, frame/dvm/rpc/runtime-api/Cargo.toml, frame/evm/Cargo.toml, frame/evm/precompile/contracts/bridge/bsc/Cargo.toml, frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml, frame/evm/precompile/contracts/bridge/s2s/Cargo.toml, frame/evm/precompile/contracts/dispatch/Cargo.toml, frame/evm/precompile/contracts/transfer/Cargo.toml, frame/wormhole/issuing/ethereum/Cargo.toml, frame/wormhole/issuing/s2s/Cargo.toml, node/rpc/Cargo.toml, node/runtime/pangolin/Cargo.toml, node/runtime/template/Cargo.toml, node/service/Cargo.toml
I found there are 2 incompatible versions.
@AsceticBear
=> Downgrade Frontier

Cargo.lock
Including https://github.com/darwinia-network/frontier/commit/1315cde4389d2805427b1d160a2c6cf84d8136ee
=> Remove Base Fee Event

Cargo.lock, frame/dvm/evm/precompiles/bridge/bsc/src/lib.rs, frame/dvm/evm/precompiles/bridge/s2s/src/lib.rs, frame/dvm/evm/precompiles/dispatch/Cargo.toml, frame/dvm/evm/precompiles/dispatch/src/lib.rs, frame/dvm/evm/precompiles/transfer/Cargo.toml, frame/dvm/evm/precompiles/transfer/src/kton.rs, frame/dvm/evm/precompiles/transfer/src/lib.rs, frame/dvm/evm/precompiles/transfer/src/ring.rs, frame/dvm/evm/precompiles/utils/src/lib.rs
No logic change. This is an easy one to review.
=> Simplify return error way

frame/dvm/ethereum/src/mock.rs, frame/dvm/evm/src/lib.rs, frame/dvm/evm/src/tests.rs, frame/wormhole/issuing/s2s/src/mock.rs, node/cli/Cargo.toml, node/runtime/pangolin/src/pallets/evm.rs, node/runtime/pangoro/src/pallets/evm.rs, node/runtime/template/src/pallets/evm.rs
- `EVMCurrencyAdapter` -> `EVMCurrencyAdapter<FindAccountFromAuthorIndex<Self, Babe>>`
=> Fix priority fee to block author

Cargo.lock, frame/dvm/ethereum/Cargo.toml, frame/dvm/evm/Cargo.toml, frame/dvm/evm/precompiles/bridge/bsc/Cargo.toml, frame/dvm/evm/precompiles/bridge/ethereum/Cargo.toml, frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml, frame/dvm/evm/precompiles/dispatch/Cargo.toml, frame/dvm/evm/precompiles/transfer/Cargo.toml, frame/dvm/evm/precompiles/utils/Cargo.toml, frame/dvm/evm/precompiles/utils/macro/Cargo.toml, frame/wormhole/issuing/ethereum/Cargo.toml, frame/wormhole/issuing/s2s/Cargo.toml, node/cli/Cargo.toml, node/rpc/Cargo.toml, node/runtime/pangolin/Cargo.toml, node/runtime/pangoro/Cargo.toml, node/runtime/template/Cargo.toml, node/service/Cargo.toml, primitives/evm-trace/ext/Cargo.toml, primitives/evm-trace/tracer/Cargo.toml
@AurevoirXavier Please help draft a new release for pangolin/pangoro after this merge.
=> Anchor v0.12.1 deps

node/runtime/pangolin/Cargo.toml, node/runtime/pangoro/Cargo.toml
Add `on-chain-release-build`.
Remove `no-wasm`.
=> Adjust Runtime Features

Cargo.lock, frame/fee-market/Cargo.toml, frame/fee-market/src/benchmarking.rs, frame/fee-market/src/lib.rs, frame/fee-market/src/s2s/payment.rs, frame/fee-market/src/tests.rs
`AccoundId` is not more defaultable.
Hence we need to change `ValueQuery` to `OptionQuery`.
Please fix the code logic. @AsceticBear
=> Update Substrate and Fix `darwinia-fee-market`

Cargo.lock, frame/dvm/evm/precompiles/bridge/bsc/src/lib.rs, frame/dvm/evm/precompiles/bridge/ethereum/Cargo.toml, frame/dvm/evm/precompiles/bridge/ethereum/src/lib.rs, frame/dvm/evm/precompiles/bridge/s2s/Cargo.toml, frame/dvm/evm/precompiles/bridge/s2s/src/lib.rs, frame/dvm/evm/precompiles/dispatch/src/lib.rs, frame/dvm/evm/precompiles/transfer/Cargo.toml, frame/dvm/evm/precompiles/transfer/src/kton.rs, frame/dvm/evm/precompiles/transfer/src/lib.rs, frame/dvm/evm/precompiles/transfer/src/ring.rs, frame/dvm/evm/precompiles/transfer/src/tests/mock.rs, frame/dvm/evm/precompiles/transfer/src/tests/test.rs, frame/dvm/evm/precompiles/utils/macro/Cargo.toml, frame/dvm/evm/precompiles/utils/macro/src/lib.rs, frame/dvm/evm/precompiles/utils/macro/tests/tests.rs, frame/dvm/evm/precompiles/utils/src/lib.rs
As the issue state, change the original `ExitError::Other(xxx)` to `ExitRevert::Reverted`.
=> Change precompile error to revert

frame/balances/src/migration.rs, node/runtime/pangolin/src/migrations.rs, node/runtime/pangolin/src/pallets/fee_market.rs, node/runtime/pangoro/src/migrations.rs, node/runtime/pangoro/src/pallets/fee_market.rs
Companion for darwinia https://github.com/darwinia-network/darwinia/pull/875
=> Shorten Feemarket Slot 

frame/staking/src/darwinia_tests/bonding.rs, frame/staking/src/impls.rs, frame/staking/src/lib.rs, frame/staking/src/mock.rs, frame/staking/src/substrate_tests.rs
Part of #1238.
There might be some empty ledger on the chain.
Should we clean the old staking data within this runtime upgrade? @HackFisher
=> Handling Zero ED

Cargo.lock, node/runtime/pangolin/Cargo.toml, node/runtime/pangolin/src/pallets/evm.rs, node/runtime/pangoro/Cargo.toml, node/runtime/pangoro/src/pallets/evm.rs
=> Add Precompile `blake2`

.github/workflows/checks.yml, node/runtime/pangolin/Cargo.toml, node/runtime/pangoro/Cargo.toml, rust-toolchain.toml
Fix the CI.
And this is a part of https://github.com/darwinia-network/darwinia-common/issues/1248.
=> Optional Benchmark

frame/balances/src/migration.rs, frame/support/src/structs.rs, rust-toolchain.toml
=> Fix Staking Locked Amount

frame/staking/src/impls.rs, frame/staking/src/lib.rs, frame/support/src/structs.rs
=> Correct Total Unbonding Calculation (#1234)

Cargo.lock, node/runtime/pangolin/Cargo.toml, node/runtime/pangolin/src/pallets/evm_.rs, node/runtime/pangoro/Cargo.toml, node/runtime/pangoro/src/pallets/evm_.rs
Ethereum precompile list:
https://github.com/ethereum/go-ethereum/blob/bd6879ac518431174a490ba42f7e6e822dcb3ee1/core/vm/contracts.go#L51-L60
=> Add Ethereum precompiles

tests/dvm/frontier/tests/test-fee-history.ts, tests/dvm/frontier/tests/test-max-priority-fee-per-gas-rpc.ts
Close https://github.com/darwinia-network/darwinia-common/issues/1212 after this merge.
=> Companion for tests after frontier upgrade

Cargo.lock, node/rpc/src/lib.rs, node/rpc/src/template.rs, node/service/src/service/dvm.rs
See https://github.com/darwinia-network/frontier/commit/b189ca5509f4759b7a850036befcaceb468cf452
=> Upgrade frontier to fix schema issues

.github/workflows/checks.yml, Cargo.lock, node/primitives/Cargo.toml, node/primitives/src/lib.rs, node/runtime/pangolin/src/pallets/system.rs, node/runtime/pangoro/src/pallets/system.rs, node/runtime/template/src/pallets/system.rs
=> Custom MultiAddress

node/runtime/common/src/impls.rs
=> Remove Duplicate Event

frame/bridge/ecdsa-authority/src/lib.rs, frame/bridge/ecdsa-authority/src/primitives.rs, frame/bridge/ecdsa-authority/src/tests.rs
- More tests
- Free to submit the first-correct signature
=> Free to Submit the First-Correct Signature

frame/bridge/ecdsa-authority/src/lib.rs, frame/bridge/ecdsa-authority/src/mock.rs, frame/bridge/ecdsa-authority/src/primitives.rs, frame/bridge/ecdsa-authority/src/tests.rs
=> Emmit Commitment

tests/local-testnet/deploy.sh
=> Improve Local Testent Script

node/runtime/pangolin/src/pallets/ecdsa_authority.rs, node/runtime/pangoro/src/pallets/ecdsa_authority.rs
=> Rename to `MaxEcdsaAuthorities`

Cargo.lock, frame/dvm/evm/precompiles/state-storage/src/tests.rs, node/runtime/pangolin/src/pallets/fee_market.rs, node/runtime/pangoro/src/pallets/fee_market.rs
> https://github.com/darwinia-network/darwinia-messages-substrate/pull/175
=> Sync `darwinia-message-bridges` Updates

Cargo.lock
To include https://github.com/darwinia-network/frontier/commit/72bf8c397a5921c8bdac61aa4e42cb6fd98f5c7d
Need a companion to the `darwinia-v0.12.4` branch under this repo after merge.
=> Bump Frontier

node/runtime/pangolin/src/migrations.rs, node/runtime/pangoro/src/migrations.rs
=> Delete the staled order 

frame/bridge/ecdsa-authority/src/lib.rs, frame/bridge/ecdsa-authority/src/tests.rs
=> Refresh Message Root After Authority Changed

node/runtime/pangolin/src/lib.rs, node/runtime/pangoro/src/lib.rs
https://github.com/darwinia-network/darwinia-common/pull/1426#issuecomment-1238843029
=> Bump Runtime Version

Cargo.lock, frame/dvm/evm/precompiles/state-storage/src/tests.rs, node/runtime/common/Cargo.toml, node/runtime/common/src/impls.rs, node/runtime/pangolin/src/bridges_message/pangolin_parachain.rs, node/runtime/pangolin/src/bridges_message/pangoro.rs, node/runtime/pangolin/src/pallets/fee_market.rs, node/runtime/pangoro/src/bridges_message/pangolin.rs, node/runtime/pangoro/src/pallets/fee_market.rs
Companions for :
1. https://github.com/darwinia-network/darwinia-messages-substrate/pull/189
2. https://github.com/darwinia-network/darwinia-messages-substrate/pull/192
3. https://github.com/darwinia-network/darwinia-messages-substrate/pull/201
=> Companions from `darwinia-message-substrate`

node/runtime/pangolin/src/bridges_message/pangolin_parachain.rs, node/runtime/pangolin/src/bridges_message/pangolin_parachain_alpha.rs, node/runtime/pangolin/src/lib.rs, node/runtime/pangolin/src/migrations.rs, node/runtime/pangolin/src/pallets/bridge_parachains.rs
=> Unify name spec

frame/staking/src/darwinia_tests/depositing.rs, frame/staking/src/impls.rs, frame/staking/src/lib.rs, frame/staking/src/slashing.rs, frame/support/src/structs.rs
=> Refresh unbondings automatically
