.travis.yml

We ran into a compile problem with nightly around Feb 2020, and the issue may be solved.
So we free the version limitation.
- free the nightly version
- fix #32

ci: use the latest nightly

---

frame/bridge/eth/offchain/src/lib.rs
frame/bridge/eth/offchain/src/tests.rs

- redundant with multiple ethereum resource
- get block from ethscan if api key provided else from ethgateway
- https://github.com/darwinia-network/darwinia/issues/371

Multiple Ethereum resource

---

frame/bridge/eth/offchain/src/lib.rs
frame/bridge/eth/offchain/src/tests.rs

- fetch ethereum header a nonexist domain, such that the offchain worker is ready to be adapted by darwinia.js
- use easy-testing feature to change url to `https://cloudflare-eth.com/`
- fix #74

request from a dummy domain

---

primitives/eth-primitives/src/header.rs

More strict check even if hashes equal since EthHeader could be decoded from dispatch call by external
Closes #59

More strict check for EthHeader PartialEq

---

frame/bridge/eth/offchain/src/lib.rs

There is a shadow service provided, so we make this domain as default value.
- modify default url for shadow service to shadow.darwinia.network (line 84)
- apply rustfmt

Modify default url for shadow service

---

bin/node-template/runtime/src/lib.rs
frame/bridge/relayer-game/README.md
frame/bridge/relayer-game/src/lib.rs
frame/bridge/relayer-game/src/mock.rs
frame/support/src/traits.rs

A new event added.
Once a new round started, it will deposit an event `NewRound`.
```rust
tuple NewRound(
GameId(MMR Last Leaf): BlockNumber, // this round of which game also the last leaf, MMR::new(block_number_to_mmr_size(last_leaf))
Samples: Vec<BlockNumber>,          // the samples need to submit for this round
MMR Members: Vec<BlockNumber>,      // MerkleProof::gen_proof(members)
)
```

Relayer Game Event

---

bin/node-template/runtime/darwinia_types.json
bin/node-template/runtime/polkadot_compatible_types.json

Javascript program appears `Could not convert` errors because we don't have `{"Address": "AccountId","LookupSource": "AccountId"}` in our `types.json`, ref to the FAQ [the-node-returns-a-could-not-convert-error-on-send][0]
[0]: https://polkadot.js.org/api/start/FAQ.html#the-node-returns-a-could-not-convert-error-on-send

Add spec name types to adapt node-template

---

frame/header-mmr/src/lib.rs
frame/header-mmr/src/tests.rs

```rust
// T::Hash impl Default
pub MMRNodeList get(fn mmr_node_list): map hasher(identity) u64 => T::Hash;
fn get_elem(&self, pos: u64) -> Result<Option<T::Hash>> {
Ok(Some(<Module<T>>::mmr_node_list(pos)))
}
```
This will always return a valid hash. Get mmr root will never fail. Even the size is wrong.

fix: always return some

---

frame/bridge/relay-authorities/src/lib.rs

This call is dangerous. Should only be used in testnet.

feat(relay authorities): reset authorities

---

frame/bridge/relay-authorities/src/lib.rs
frame/bridge/relay-authorities/src/mock.rs
frame/bridge/relay-authorities/src/test.rs

1. don't need to submit mmr root
1. should not `+1` on signatures length

Code Optimize & Fix Relay Authorities Bug

---

bin/node/runtime/pangolin/src/weights/darwinia_staking.rs
frame/staking/src/default_weights.rs
frame/staking/src/lib.rs
frame/staking/src/offchain_election.rs
frame/staking/src/slashing.rs
frame/staking/src/substrate_tests.rs
frame/support/src/structs.rs

A lot of people unbond their assets accidentally.
With this feature, they don't need to wait 14 days and bond again.

Feat Staking Rebond

---

frame/bridge/relay-authorities/src/lib.rs
frame/bridge/relay-authorities/src/test.rs

A custom migration might need. Just label D1 here.

Update Relay Authorities Protocol

---

Cargo.lock
bin/node/runtime/pangolin/polkadot-compatible-types.json
bin/node/runtime/pangolin/src/lib.rs
bin/node/runtime/pangolin/types.json
frame/bridge/ethereum/backing/src/lib.rs
frame/bridge/ethereum/backing/src/mock.rs
frame/bridge/ethereum/backing/src/test_with_relay.rs
frame/bridge/relay-authorities/Cargo.toml
frame/bridge/relay-authorities/src/lib.rs
frame/bridge/relay-authorities/src/mock.rs
frame/bridge/relay-authorities/src/test.rs
primitives/relay/src/relay_authorities.rs

A custom migration needed for Crab.

Refactor Relay Authorities

---

frame/evm/src/runner/stack.rs

Check firstly and withdraw later.
The same with https://github.com/paritytech/frontier/blob/master/frame/evm/src/runner/stack.rs#L84-L89

Check nonce firstly and withdraw fee later

---

bin/node/runtime/pangolin/src/dvm.rs
frame/dvm/src/lib.rs
frame/dvm/src/mock.rs

1. In the dvm pallet, we can directly use the evm pallet `AddressMapping` type.
2. `transaction_hashes` related operations have been moved to the `Hashes::from_block()`

Some chores about dvm 

---

Cargo.lock
bin/node/runtime/pangolin/Cargo.toml
bin/node/runtime/pangolin/src/lib.rs
frame/dvm/Cargo.toml
frame/dvm/src/lib.rs

```sh
$ ./target/release/drml try-runtime live http://localhost:9933
2021-04-20 13:57:43 `pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0    
2021-04-20 13:57:43 [#0] 🗳  Finalized election round with compute ElectionCompute::OnChain.    
2021-04-20 13:57:43 [0] 💸 new validator set of size 1 has been processed for era 1    
2021-04-20 13:57:43 [darwinia-claims] Genesis Claims List is Set to EMPTY    
2021-04-20 13:57:43 initializing remote client to "http://localhost:9933"    
2021-04-20 13:57:43 scraping keypairs from remote node http://localhost:9933 @ 0x9de6f0e79a771f6fdbae5dadd58aef9f37abd8c225c9fcc072e5bf66a907f320    
2021-04-20 13:57:43 downloading data for all modules.    
2021-04-20 13:57:43 extending externalities with 1 manually injected keys …
```

Test dvm migration use try-runtime

---

Cargo.lock
frame/evm/precompile/contracts/kton/Cargo.toml
frame/evm/precompile/contracts/kton/src/lib.rs
frame/evm/precompile/contracts/kton/src/util.rs

The runner call function always returns `Ok(...)` even an inner execution error happened.
We should capture the `exit_reason` contained in the call result and make a decision to commit or discard state change.

Capture runner call error

---

bin/node/runtime/pangolin/src/lib.rs
frame/democracy/src/lib.rs
frame/dvm-dynamic-fee/src/lib.rs

1. There is no need to output the target gas price event for each block.
2. Move `kill()` into the `on_initialize`, then you can view`TargetMinGasPrice` value in explorer.

Remove Event `TargetMinGasPriceSet`

---

bin/node/runtime/pangolin/src/lib.rs
frame/bridge/ethereum/issuing/src/lib.rs
frame/dvm/rpc/runtime-api/src/lib.rs
frame/dvm/rpc/src/eth.rs
frame/dvm/rpc/src/eth_pubsub.rs
frame/dvm/rpc/src/lib.rs
frame/dvm/rpc/src/net.rs
frame/dvm/rpc/src/web3.rs
frame/dvm/src/account_basic.rs
frame/dvm/src/lib.rs
frame/dvm/src/mock.rs
frame/dvm/src/tests.rs

The old version metadata:
```sh
$ subsee -p Ethereum > eth_old.json
{"name":"Ethereum","storage":{"prefix":"Ethereum","entries":[{"name":"Pending","modifier":"Default","ty":{"Plain":"Vec<(ethereum::Transaction, TransactionStatus, ethereum::Receipt)>"},"default":[0],"documentation":[" Current building block's transactions and receipts."]},{"name":"CurrentBlock","modifier":"Optional","ty":{"Plain":"ethereum::Block"},"default":[0],"documentation":[" The current Ethereum block."]},{"name":"CurrentReceipts","modifier":"Optional","ty":{"Plain":"Vec<ethereum::Receipt>"},"default":[0],"documentation":[" The current Ethereum receipts."]},{"name":"CurrentTransactionStatuses","modifier":"Optional","ty":{"Plain":"Vec<TransactionStatus>"},"default":[0],"documentation":[" The current transaction …
```

Upgrade Ethereum pallet to FRAMEv2

---

bin/node/runtime/pangolin/src/lib.rs
frame/dvm-dynamic-fee/src/lib.rs
frame/evm/precompile/contracts/kton/src/lib.rs
frame/evm/src/lib.rs
frame/evm/src/runner/mod.rs
frame/evm/src/runner/stack.rs
frame/evm/src/tests.rs

The old version metadata:
```sh
$ subsee -p EVM > evm_old.json
{"name":"EVM","storage":{"prefix":"EVM","entries":[{"name":"AccountCodes","modifier":"Default","ty":{"Map":{"hasher":"Blake2_128Concat","key":"H160","value":"Vec<u8>","unused":false}},"default":[0],"documentation":[]},{"name":"AccountStorages","modifier":"Default","ty":{"DoubleMap":{"hasher":"Blake2_128Concat","key1":"H160","key2":"H256","value":"H256","key2_hasher":"Blake2_128Concat"}},"default":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"documentation":[]}]},"calls":[{"name":"call","arguments":[{"name":"source","ty":"H160"},{"name":"target","ty":"H160"},{"name":"input","ty":"Vec<u8>"},{"name":"value","ty":"U256"},{"name":"gas_limit","ty":"u64"},{"name":"gas_price","ty":"U256"},{"name":"nonce","ty":"Opti …
```

Upgrade EVM pallet to FRAMEv2

---

bin/node/cli/src/chain_spec.rs
bin/node/runtime/pangolin/src/pallets/membership.rs

We should initialize the collective members from these 2 pallets
1. Membership [Genesis](https://github.com/paritytech/substrate/blob/master/frame/membership/src/lib.rs#L88) <-> [Runtime Configuration](https://github.com/darwinia-network/darwinia-common/blob/master/bin/node/runtime/pangolin/src/pallets/membership.rs#L26)
2. Elections phragmen [Genesis](https://github.com/paritytech/substrate/blob/master/frame/elections-phragmen/src/lib.rs#L699) <-> [Runtime Configuration](https://github.com/darwinia-network/darwinia-common/blob/master/bin/node/runtime/pangolin/src/pallets/elections_phragmen.rs#L27)

Correct Collective Genesis

---

Cargo.lock
frame/bridge/ethereum/backing/Cargo.toml
frame/bridge/ethereum/issuing/contract/Cargo.toml
frame/dvm/Cargo.toml
frame/evm/precompile/contracts/transfer/Cargo.toml
frame/support/Cargo.toml
primitives/contract/Cargo.toml
primitives/ethereum-primitives/Cargo.toml

Anchor the libraries to a particular tag. Avoid getting updated accidentally while running `cargo update` globally.

Tag Thirdparty Libraries

---

frame/bridge/ethereum/relay/Cargo.toml

Which fix https://github.com/darwinia-network/bridger/pull/206#issuecomment-887182320
Once some feature was enabled within the whole compile-tree, it was enabled. 
So, we miss this before.

Add Missing Feature Serde for STD

---

frame/bridge/ethereum/backing/Cargo.toml
frame/bridge/ethereum/relay/Cargo.toml
frame/bridge/ethereum/relay/src/lib.rs

Serde should always enable under STD ENV. Because `GenesisBuilder` is always under STD ENV.

Remove Unecessary Feature Control for Pallets

---

Cargo.lock
bin/node/runtime/pangolin/src/pallets/evm_.rs
frame/bridge/s2s/issuing/src/tests.rs
frame/dvm/src/mock.rs
frame/dvm/src/tests.rs
frame/evm/src/lib.rs
frame/evm/src/tests.rs

Companion pr in darwinia: https://github.com/darwinia-network/darwinia/pull/691

Remove useless type in evm pallet

---

node/primitives/bridge/src/lib.rs

The bridge need these key to write data to pallet

Pangoro Bridge Primitives

---

.github/workflows/release.yml
vercel.json

When a new tag is created (Must start with `v`). will build and deploy rust docs. when the deployment is successful, the domain darwinia-common.vercel.app can be accessed rust docs

Add Rustdoc to CI

---

frame/evm/precompile/contracts/encoder/src/lib.rs
frame/support/src/lib.rs
frame/wormhole/backing/s2s/src/lib.rs
frame/wormhole/backing/s2s/src/tests.rs
frame/wormhole/issuing/s2s/src/lib.rs
frame/wormhole/issuing/s2s/src/tests.rs
node/runtime/pangolin/polkadot-compatible-types.json
node/runtime/pangolin/src/pallets/from_substrate_issuing_.rs
node/runtime/pangolin/types.json
node/runtime/pangoro/src/pallets/to_substrate_backing_.rs

To avoid the type conflict of this update.
https://github.com/paritytech/parity-bridges-common/pull/1152

BridgeMessageId=>TokenMessageId

---

node/runtime/pangolin/polkadot-compatible-types.json

```
{
"IndividualExposure": {
"who": "AccountId",
"ring_balance": "Compact<Balance>",
"kton_balance": "Compact<Balance>",
"power": "Power"
},
"AccountData": {
"free": "Balance",
"reserved": "Balance",
"free_kton": "Balance",
"reserved_kton": "Balance"
},
"BalanceLock": {
"id": "LockIdentifier",
"lock_for": "LockFor",
"lock_reasons": "LockReasons"
},
"LockReasons": {
"_enum": {
"Fee": null,
"Misc": null,
"All": null
}
}
}
```
Staking -> Payouts -> Own stashes
cc @WoeOm

Fix Polkadot JS Balance Lock Relateds

---

node/runtime/pangolin/src/lib.rs
node/runtime/pangoro/src/lib.rs

https://github.com/darwinia-network/bridger/blob/81ffefaaa00d94689e70a8ed572210700d6b0466/components/client-pangolin-s2s/src/api.rs#L125
https://github.com/darwinia-network/bridger/blob/81ffefaaa00d94689e70a8ed572210700d6b0466/components/client-pangoro-s2s/src/api.rs#L125
The bridger will use this call to build transactions.
Related: https://github.com/darwinia-network/bridger/pull/308

Expose fee market call

---

.github/workflows/ci.yml
Cargo.lock
rust-toolchain.toml

#879 fixed.
So, release the lock and go to enjoy the latest Rust features.

Use Nightly Toolchain

---

frame/wormhole/issuing/s2s/src/benchmarking.rs

```rs
$ cargo check --release --features runtime-benchmarks
error[E0432]: unresolved import `dp_asset::token`
--> frame/wormhole/issuing/s2s/src/benchmarking.rs:26:15
|
26 | use dp_asset::token::{TokenMetadata, NATIVE_TOKEN_TYPE};
|               ^^^^^ could not find `token` in `dp_asset`
For more information about this error, try `rustc --explain E0432`.
error: could not compile `from-substrate-issuing` due to previous error
warning: build failed, waiting for other jobs to finish...
```

Fix compile in benchmark mode

---

Cargo.lock
node/service/Cargo.toml
node/service/src/chain_spec/mod.rs
node/service/src/chain_spec/pangolin.rs
node/service/src/chain_spec/pangoro.rs

> ```
> This decouples the light-sync state from chain spec. First, the
> light-sync state currently only works with BABE+Grandpa, so not
> all Substrate based chains can use this feature. The next problem was
> also that this pulled the sc-consensus-babe and sc-finality-grandpa
> crate into sc-chain-spec.
>
> If a chain now wants to support the light-sync state, it needs to add
> the LightSyncStateExtension to the chain spec as an extension. This is
> documented in the crate level docs of sc-sync-state-rpc. If this
> extension is not available, SyncStateRpc fails at initialization.
> ```
If we disable this extension the node will fail to boot.

Fix Sync State

---

Cargo.lock
Cargo.toml
client/dvm/rpc/Cargo.toml
frame/dvm/Cargo.toml
frame/evm/Cargo.toml
frame/evm/precompile/contracts/blake2/Cargo.toml
frame/evm/precompile/contracts/bn128/Cargo.toml
frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
frame/evm/precompile/contracts/curve25519/Cargo.toml
frame/evm/precompile/contracts/dispatch/Cargo.toml
frame/evm/precompile/contracts/ed25519/Cargo.toml
frame/evm/precompile/contracts/modexp/Cargo.toml
frame/evm/precompile/contracts/sha3fips/Cargo.toml
frame/evm/precompile/contracts/simple/Cargo.toml
frame/evm/precompile/contracts/transfer/Cargo.toml
frame/evm/precompile/contracts/utils/Cargo.toml
frame/evm/precompile/contracts/utils/macro/Cargo.toml
frame/wormhole/issuing/s2s/Cargo.toml
node/runtime/pangolin/Cargo.toml
primitives/evm/Cargo.toml
primitives/evm/trace/events/Cargo.toml
primitives/evm/trace/tracer/Cargo.toml

Use `[patch.crates-io]` to replace evm crates dep, this does not affect `evm-tracing`  feature compile. Much easier to maintain.

Update evm crates path

---

frame/dvm/src/account_basic.rs
frame/dvm/src/tests.rs
frame/support/src/evm.rs

No logic changes. Just some refactor works to make the `account_basic` tests easy to maintain.

Use `decimal_convert` to refactor AccountBasic tests

---

frame/fee-market/src/lib.rs
frame/fee-market/src/s2s/mod.rs
frame/fee-market/src/s2s/payment.rs
frame/fee-market/src/tests.rs
node/runtime/pangolin/types.json
primitives/fee-market/src/lib.rs

Close #1009 
After discussing with Yalin, both s2s message and fee market pallets will clean the old order/message data as time goes by. So it is better to keep all these fields about the order status.

Add fee market slash event

---

frame/evm/src/lib.rs

When initializing some accounts in the Genesis build, we should increase account nonce as well as balance.

Initialize account nonce in building genesis

---

Cargo.lock
client/dvm/db/Cargo.toml
client/dvm/rpc/Cargo.toml
frame/dvm/Cargo.toml
frame/dvm/rpc/Cargo.toml
frame/dvm/rpc/runtime-api/Cargo.toml
frame/dvm/src/lib.rs
frame/dvm/src/mock.rs
frame/dvm/src/tests.rs
frame/evm/Cargo.toml
frame/evm/precompile/contracts/bridge/bsc/Cargo.toml
frame/evm/precompile/contracts/bridge/ethereum/Cargo.toml
frame/evm/precompile/contracts/bridge/s2s/Cargo.toml
frame/evm/precompile/contracts/dispatch/Cargo.toml
frame/evm/precompile/contracts/transfer/Cargo.toml
frame/support/src/evm.rs
frame/wormhole/issuing/ethereum/Cargo.toml
frame/wormhole/issuing/s2s/Cargo.toml
frame/wormhole/issuing/s2s/src/mock.rs
node/rpc/Cargo.toml
node/runtime/pangolin/Cargo.toml
node/runtime/pangolin/src/lib.rs
node/runtime/template/Cargo.toml
node/runtime/template/src/lib.rs
node/service/Cargo.toml

Companion for https://github.com/paritytech/frontier/pull/482 and https://github.com/paritytech/frontier/pull/495.
> To use the new code, you need to change in your runtime checked and unchecked extrinsics to point to fp_self_contained::CheckedExtrinsic and fp_self_contained::UncheckedExtrinsic. This will also require you to implement SelfContainedCall trait for runtime Call, which the node template contains sample code.
We rely on the darwinia-frontier branch 0.12.1(The main branch is darwinia-frontier 0.12.0). Might merge these changes to 0.12.0 and upgrade to pangolin directly.

DVM signed transaction

---

.maintain/purge-large-cache.sh

Debug cache is too large.
That's the reason why CI was blocked yesterday.

Purge Debug Cache

---

frame/dvm/src/account_basic.rs
frame/dvm/src/lib.rs
frame/dvm/src/tests.rs

Close #1064, It's worth noting that the `value` field decimal is 18, the application such as `subscan` needs some work to make the display user-friendly.

Add Transfer Event for DVM

---

node/runtime/pangolin/src/lib.rs
node/runtime/pangoro/src/lib.rs

Fix
```
ERROR tokio-runtime-worker runtime: panicked at 'source slice length (32) does not match destination slice length (33)'
```

Correct BEEFY Key Length

---

frame/dvm/evm/precompiles/bridge/bsc/src/lib.rs
frame/dvm/evm/precompiles/bridge/ethereum/src/lib.rs
frame/dvm/evm/precompiles/dispatch/src/lib.rs
node/service/src/service/mod.rs

`Stopped` and `Returned` both work, but, literally, `Returned` is better.

Improve `PrecompileOutput`'s `exit_status`

---

frame/fee-market/rpc/runtime-api/src/lib.rs
frame/fee-market/rpc/src/lib.rs
frame/fee-market/src/lib.rs
frame/fee-market/src/s2s/callbacks.rs
frame/fee-market/src/s2s/payment.rs
frame/fee-market/src/tests.rs
node/runtime/common/src/impls.rs
node/runtime/pangolin/src/bridges_message/pangoro.rs
node/runtime/pangolin/src/lib.rs
node/runtime/pangolin/src/pallets/bridge_messages.rs
node/runtime/pangolin/src/pallets/fee_market.rs
node/runtime/pangoro/src/bridges_message/pangolin.rs
node/runtime/pangoro/src/lib.rs
node/runtime/pangoro/src/pallets/bridge_messages.rs
node/runtime/pangoro/src/pallets/fee_market.rs

As I didn't change the `locked_id` or `pallet_id ` of the original pangolin<> pangoro fee market config, so no migration needs.
Note: The original fee market runtime API has broken changes, add an extra `instance: u8` param.

Make fee market instantiable

---

node/runtime/pangolin/src/pallets/evm.rs
node/runtime/pangoro/src/pallets/evm.rs
tests/dvm/darwinia/tests/1-test-transfer.ts
tests/dvm/darwinia/tests/2-test-log.ts
tests/dvm/darwinia/tests/4-test-opcodes.ts

The auto-filled `max_fee_per_gas` in the metamask is much higher than our newly `gas_price` and causes `InvalidTransaction` error.

Revert gas price update

---

frame/dvm/evm/precompiles/bridge/bsc/src/lib.rs
frame/dvm/evm/precompiles/bridge/ethereum/src/lib.rs
frame/dvm/evm/precompiles/bridge/s2s/src/lib.rs

The precompile address is determined in runtime and varies in different networks. Those fixed annotations here is easy to make newbies confused.

Remove Incorrect Annotation

---

node/service/Cargo.toml

Some contracts are only deployed on the Pangoro network, add tracing runtime support the same with the Pangolin.

Enable `evm-tracing` for Pangoro

---

Cargo.lock
node/runtime/pangolin/src/pallets/evm.rs
node/runtime/pangoro/Cargo.toml
node/runtime/pangoro/src/pallets/evm.rs

See https://github.com/darwinia-network/darwinia/issues/901 and https://github.com/darwinia-network/darwinia/issues/906
1. Install dispatch precompile to the Pangoro network runtime.
2. Update `StateStorage` address to `1024`, `Dispatch` precompile address to `1025`. Leave others untouched and add some comments.

Update precompiles registered addrs

---

Cargo.lock
frame/balances/Cargo.toml
frame/balances/src/lib.rs
frame/balances/src/tests_local.rs
frame/balances/src/tests_reentrancy.rs
frame/bridge/ethereum/src/mock.rs
frame/bridge/relay-authorities/src/mock.rs
frame/bridge/relayer-game/src/mock.rs
frame/dvm/ethereum/src/mock.rs
frame/dvm/evm/precompiles/state-storage/src/tests.rs
frame/dvm/evm/precompiles/transfer/src/tests/mock.rs
frame/dvm/evm/src/tests.rs
frame/staking/src/mock.rs
frame/support/Cargo.toml
frame/support/src/lib.rs
frame/support/src/traits.rs
frame/transaction-pause/src/mock.rs
frame/wormhole/backing/ethereum/src/mock.rs
frame/wormhole/backing/s2s/src/tests.rs
frame/wormhole/issuing/s2s/src/mock.rs
node/runtime/pangolin/src/pallets/balances.rs
node/runtime/pangoro/src/pallets/balances.rs
node/runtime/template/src/pallets/balances.rs

Due to the EVM, ED must be set to 0.
So, this checker is useless now.
Close https://github.com/darwinia-network/darwinia/issues/653.
Part of #1157.
Part of #831.

Remove `DustCollector`

---

Cargo.lock
node/runtime/pangolin/src/pallets/bridge_dispatch.rs

Update `darwinia-messages-substrate` to include https://github.com/darwinia-network/darwinia-messages-substrate/pull/155.

Companion of darwinia-network/darwinia-messages-substrate#155

---

frame/dvm/ethereum/src/lib.rs
frame/dvm/ethereum/src/tests/internal.rs

For reviewer:
1. https://github.com/ethereum/EIPs/issues/155
2. https://github.com/rust-blockchain/ethereum/blob/master/src/transaction.rs#L61-L77

Avoid Using Hardcode `ChainId` for Internal Transaction

---

frame/dvm/evm/precompiles/utils/src/lib.rs

We don't need to do digest on runtime

Use const function selector

---

frame/bridge/ecdsa-authority/Cargo.toml
frame/bridge/ecdsa-authority/src/lib.rs
frame/bridge/ecdsa-authority/src/mock.rs
frame/bridge/ecdsa-authority/src/primitives.rs
frame/bridge/ecdsa-authority/src/tests.rs

Make things more friendly to bridger.
Bridger only needs to focus on `Authorities` storage while the authority set is changing.
cc @fewensa @hujw77

Use `NextAuthorities` Instead

---

node/runtime/pangolin/src/bridges_message/pangolin_parachain.rs
node/runtime/pangolin/src/bridges_message/pangoro.rs
node/runtime/pangoro/src/bridges_message/pangolin.rs

Part of #1403. If someone sends cross-chain messages to those unmonitored lanes, nothing will be seen in the target chain.
Bridger Lane Config Reference: https://github.com/darwinia-network/bridger/blob/master/.maintain/config/bridge-pangolin-pangolinparachain.toml

Only keep the lane monitored by the bridgers

---

frame/dvm/ethereum/src/mock.rs
node/runtime/pangolin/src/pallets/bridge_dispatch.rs
node/runtime/pangoro/src/pallets/bridge_dispatch.rs

Fix #1310 
1. Replace the `MaxUsableBalanceFromRelayer` validation with `BlockGasLimit`
2. Remove the duplicated validations in `call_validate`, which has been done in the `check_receiving_before_dispatch` before dispatching.

Replace `MaxUsableBalanceFromRelayer` with `BlockGasLimit`

---

Cargo.lock
frame/dvm/evm/precompiles/kton/Cargo.toml
frame/dvm/evm/precompiles/utils/src/data/tests.rs
frame/wormhole/issuing/s2s/Cargo.toml
frame/wormhole/issuing/s2s/src/mock.rs

We don't need this anymore, all the basic types that we need are in the primitive's crates.

Remove `pallet-evm`

---

Cargo.lock
node/runtime/common/src/lib.rs
node/runtime/pangolin/Cargo.toml
node/runtime/pangolin/src/lib.rs
node/runtime/pangoro/Cargo.toml
node/runtime/pangoro/src/lib.rs

I found something while exploring #1251 
Fix an invalid link and introduce a multiplier runtime test from the Polkadot to ensure the config is correct. See https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L2057-L2082

Add runtime `multiplier_tests`

---

frame/dvm/evm/precompiles/kton/src/lib.rs

Fix #1443  
Before:
```sh
$ curl -fsS https://pangoro-rpc.darwinia.network -d '{"id":1,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x01ffc9a75b5e139f00000000000000000000000000000000000000000000000000000000","gas":"0x5b8d80","to":"0x0000000000000000000000000000000000000402"},"latest"]}' -H 'Content-Type: application/json' | jq
{
"jsonrpc": "2.0",
"result": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b4f4b544f4e204552433230000000000000000000000000000000000000000000",
"id": 1
}
```
After: 
```sh
$ curl -fsS http://127.0.0.1:9933 -d '{"id":1,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x01ffc9a75b5e139f00000000000000000000000000000000000000000000000000000000","gas":"0x5b8d80","to":"0x000 …
```

Exit when elector invalid

---

rust-toolchain.toml

This version was verified by polkadot-v0.9.29.
IMO, it's safe to switch to this toolchain.

Use `nightly-2022-07-14`
